config/routes.rb
HrsiteNew::Application.routes.draw do
  require File.expand_path("../../lib/authenticated_user",__FILE__)

  scope ":locale" ,locale: /#{I18n.available_locales.join("|")}/ do
    resources :sessions, only: [:new, :create, :destroy]
    resources :contracts
    resources :educations
    resources :employees
    resources :vehicles
    resources :documents
    resources :searches ,only: [:new,:create,:show]
    resources :users ,only:[:new,:create,:update]
    root to: 'static_pages#home', :constraints => AuthenticatedUser.new(true)
    root to: 'sessions#new', :constraints => AuthenticatedUser.new(false)
    match '/help', to: 'static_pages#help'
    match '/docshow', to: 'employees#docshow'
    match '/passport', to: 'employees#passport'
    match '/iqama', to: 'employees#iqama'
    match '/visa', to: 'employees#visa'
    match '/insurance', to: 'employees#insurance'
    match '/signin', to: 'sessions#new'
    match '/signout', to: 'sessions#destroy', via: :delete
    match '/find', to: 'employees#search'
  end
  match '*path', to: redirect("/#{I18n.default_locale}/%{path}")
  match '', to: redirect("/#{I18n.default_locale}")

end

app/models/employee.rb
# == Schema Information
#
# Table name: employees
#
#  id          :integer         not null, primary key
#  empno       :string(255)
#  first_name  :string(255)
#  middle_name :string(255)
#  last_name   :string(255)
#  gender      :string(255)
#  dob         :date
#  passportno  :string(255)
#  pidate      :date
#  pedate      :date
#  iqamano     :string(255)
#  iqidate     :date
#  iqedate     :date
#  insuranceno :string(255)
#  iidate      :date
#  iedate      :date
#  visano      :string(255)
#  vidate      :date
#  vedate      :date
#  Marstatus   :string(255)
#  religion    :string(255)
#  nationality :string(255)
#  civstatus   :string(255)
#  designation :string(255)
#  department  :string(255)
#  speciali    :string(255)
#  exp         :string(255)
#  email       :string(255)
#  created_at  :datetime        not null
#  updated_at  :datetime        not null
#  image       :string(255)
#

class Employee < ActiveRecord::Base
  attr_accessible :Marstatus, :civstatus, :department, :designation, :dob, :email, :empno, :exp, :first_name, :gender, :iedate, :iidate, :insuranceno, :iqamano, :iqedate, :iqidate, :last_name, :middle_name, :nationality, :passportno, :pedate, :pidate, :religion, :speciali, :vedate, :vidate, :visano,:image
  #:image_cache
  validates :first_name, presence: true , length: { maximum: 50 }
  validates :empno, presence: true, uniqueness:{ case_sensitive: false }
  validates_length_of :empno, :minimum => 5, :maximum => 5
  validates  :iqamano, presence: true
  validates  :iqedate, presence: true
  validates  :iqidate, presence: true
  validates  :passportno, presence: true
  validates  :pedate, presence: true
  validates :pidate, presence: true
  validates :vedate, presence: true
  validates  :vidate, presence: true
  validates  :visano, presence: true
  mount_uploader :image, ImageUploader
  def self.to_csv()
    CSV.generate() do |csv|
      csv << column_names
      all.each do |employee|
        csv << employee.attributes.values_at(*column_names)
      end
    end
  end
  
  def empname
    "#{self.first_name} #{self.last_name} (#{self.empno})"
  end

  def fullname
    "#{self.first_name} #{self.last_name}"
  end

  def self.search(keyword)
    search_condition="%"+ keyword +"%"
    find(:all,:conditions =>['first_name ILIKE ? OR email ILIKE ?',search_condition,search_condition])

  end 
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_filter :signed_in_user,
                only: [:index, :edit, :update, :destroy,:docshow,:iqama,:passport,:insurance,:visa,:show,:new,:create]
  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.all

    respond_to do |format|
      format.html # index.html.erb
      format.csv { render text: @employees.to_csv }
      format.xls #{send_data @employees.to_csv(col_sep: "\t")}
      format.json { render json: @employees }
    end
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
    @employee = Employee.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @employee }
    end
  end

  # GET /employees/new
  # GET /employees/new.json
  def new
    @employee = Employee.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @employee }
    end
  end

  # GET /employees/1/edit
  def edit
    @employee = Employee.find(params[:id])
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(params[:employee])

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render json: @employee, status: :created, location: @employee }
      else
        format.html { render action: "new" }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /employees/1
  # PUT /employees/1.json
  def update
    @employee = Employee.find(params[:id])

    respond_to do |format|
      if @employee.update_attributes(params[:employee])
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee = Employee.find(params[:id])
    @education = Education.find_by_empno(@employee.empno) 
    if @education
      @education.destroy
    end
    @contract = Contract.find_by_empno(@employee.empno)
    if @contract
      @contract.destroy
    end
    @document = Document.find_by_empno(@employee.empno)
    if @document
      @document.destroy
    end
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url }
      format.json { head :no_content }
    end
  end

  def docshow
  end
  
  def passport
    @employees=Employee.all
      #format.json { render json: @employee }
  end
  
  def iqama
    @employees=Employee.all
  end
  
  def visa
    @employees=Employee.all
  end
  
  def insurance
    @employees=Employee.all
  end

  def search
    @employees=Employee.search(params[:keyword].downcase)
    respond_to do |format|
      format.html # index.html.erb
      format.csv { render text: @employees.to_csv }
      format.xls #{send_data @employees.to_csv(col_sep: "\t")}
      format.json { render json: @employees }
    end
  end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
<%= simple_form_for @employee, :html => {:multipart => true ,:class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.input :empno%>
    <%= f.input :first_name%>
    <%= f.input :middle_name%>
    <%= f.input :last_name%>
    <%= f.input :gender,collection:[[t("helpers.label.employee.male").html_safe,"male"],[t("helpers.label.employee.female").html_safe,"female"]], as: :radio, :class=> 'checkbox inline'%>
    <%= f.input :dob,end_year: Date.today.year,start_year:1900 %>
  </div>
  <div class="control-group">
    <%= f.input :passportno%>
    <%= f.input :pidate,end_year: Date.today.year,start_year:1960%>
    <%= f.input :pedate,end_year: Date.today.year+40,start_year:Date.today.year%>
    <%= f.input :iqamano%>
    <%= f.input :iqidate,end_year: Date.today.year,start_year:1960%>
    <%= f.input :iqedate,end_year: Date.today.year+5,start_year:Date.today.year%>
    <%= f.input :insuranceno%>
    <%= f.input :iidate,end_year: Date.today.year,start_year:1960 %>
    <%= f.input :iedate,end_year: Date.today.year+40,start_year:Date.today.year %>
    <%= f.input :visano%>
    <%= f.input :vidate,end_year: Date.today.year,start_year:1960 %>
    <%= f.input :vedate,end_year: Date.today.year+10,start_year:Date.today.year %>
  </div>
  <div class="control-group">
    <%= f.input :Marstatus, collection:[[t("helpers.label.employee.single").html_safe ,"single"],[t("helpers.label.employee.married").html_safe ,"married"]],as: :radio_buttons %>
    <%= f.input :religion,collection:[[t("helpers.label.employee.mus").html_safe ,"muslim"],[t("helpers.label.employee.nmus").html_safe ,"nonmuslim"]],include_blank: false %>
    <%= f.input :nationality, as: :country,include_blank: false %>
    <%= f.input :civstatus%>
    <%= f.input :designation%>
    <%= f.input :department%>
    <%= f.input :speciali%>
    <%= f.input :exp%>
    <%= f.input :email,placeholder:'user@domain.com'%>
  </div>
  <div class="control-group">

    <div class="attach-set">
      <%= f.label t("helpers.label.employee.image").html_safe %> &nbsp
      <%= f.file_field :image, label: "Select image" %>
    </div>
  </div>  
  <div class="form-actions">
    <%= f.button :submit ,:class => 'btn btn-primary'%>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),employees_path, :class => 'btn' %>
  </div>
<% end %>

app/views/employees/docshow.html.erb
<%- model_class = Employee -%>
<div class="page-header">
  <h1>Select <%=t '.title', :default => model_class.model_name.human.titleize %> Document</h1>
</div>
  <br/>
  <br/>
<div id="hi">
  <div class="row">
    <h3><div class="span6 text-center"><%= link_to "Passport", passport_path,{class: "link"}%></div></h3>
    <h3><div class="span6 text-center"><%= link_to "Iqama", iqama_path,{class: "link"}%></div></h3>
  </div>
  <br/><br/><br/>
  <br/><br/><br/>
  <div class="row">
    <h3><div class="span6 text-center"><%= link_to "Visa", visa_path,{class: "link"}%></div></h3>
    <h3><div class="span6 text-center"><%= link_to "Insurance", insurance_path,{class: "link"}%></div></h3>
  </div>  
</div>

app/views/employees/edit.html.erb
<%- model_class = Employee -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/employees/index.html.erb
<%- model_class = Employee -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>S#</th>
      <th><%= model_class.human_attribute_name(:empno) %></th>
      <th><%= model_class.human_attribute_name(:first_name) %></th>
      <th><%= model_class.human_attribute_name(:middle_name) %></th>
      <th><%= model_class.human_attribute_name(:last_name) %></th>
      <th><%= model_class.human_attribute_name(:dob) %></th>
      <th><%= model_class.human_attribute_name(:nationality) %></th>
      <th><%= model_class.human_attribute_name(:designation) %></th>
      <th><%= model_class.human_attribute_name(:department) %></th>
      <th><%= model_class.human_attribute_name(:exp) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @employees.each_with_index do |employee,i| %>
      <tr>
        <td><%= link_to (i+1), employee_path(employee),{class: "link"} %></td>
        <td><%= employee.empno %></td>
        <td><%= link_to employee.first_name,employee_path(employee),{class: "link"} %></td>
        <td><%= employee.middle_name %></td>
        <td><%= employee.last_name %></td>
        <td><%= employee.dob %></td>
        <td><%= employee.nationality %></td>
        <td><%= employee.designation %></td>
        <td><%= employee.department %></td>
        <td><%= employee.exp %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_employee_path(employee), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      employee_path(employee),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<div class="form-actions">
<%= link_to t('.new', :default => t("helpers.links.new")),
            new_employee_path,
            :class => 'btn btn-primary' %>
<%= link_to "To Excel",employees_path(format: "xls"),:class => 'btn btn-mini' %>
</div>

app/views/employees/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">Employee No</Data></Cell>
        <Cell><Data ss:Type="String">First Name</Data></Cell>
        <Cell><Data ss:Type="String">Middle Name</Data></Cell>
        <Cell><Data ss:Type="String">Last Name</Data></Cell>
        <Cell><Data ss:Type="String">Gender</Data></Cell>
        <Cell><Data ss:Type="String">Date of Birth</Data></Cell>
        <Cell><Data ss:Type="String">Passport No</Data></Cell>
        <Cell><Data ss:Type="String">Passport Issue</Data></Cell>
        <Cell><Data ss:Type="String">Passport Expiry</Data></Cell>
        <Cell><Data ss:Type="String">Iqama No</Data></Cell>
        <Cell><Data ss:Type="String">Iqama Issue</Data></Cell>
        <Cell><Data ss:Type="String">Iqama Expiry</Data></Cell>
        <Cell><Data ss:Type="String">Insurance No</Data></Cell>
        <Cell><Data ss:Type="String">Insurance Issue</Data></Cell>
        <Cell><Data ss:Type="String">Insurance Expiry</Data></Cell>
        <Cell><Data ss:Type="String">Visa No</Data></Cell>
        <Cell><Data ss:Type="String">Visa Issue</Data></Cell>
        <Cell><Data ss:Type="String">Visa Expiry</Data></Cell>
        <Cell><Data ss:Type="String">Marital Stat</Data></Cell>
        <Cell><Data ss:Type="String">Religion</Data></Cell>
        <Cell><Data ss:Type="String">Nationality</Data></Cell>
        <Cell><Data ss:Type="String">Civil Status</Data></Cell>
        <Cell><Data ss:Type="String">Designation</Data></Cell>
        <Cell><Data ss:Type="String">Department</Data></Cell>
        <Cell><Data ss:Type="String">Specialisation</Data></Cell>
        <Cell><Data ss:Type="String">Experience</Data></Cell>
        <Cell><Data ss:Type="String">Email</Data></Cell>
      </Row>




    <% @employees.each do |employee| %>
      <Row>
        <Cell><Data ss:Type="String"><%= employee.empno %></Data></Cell>
        <Cell><Data ss:Type="String"><%= employee.first_name %></Data></Cell>
        <Cell><Data ss:Type="String"><%= employee.middle_name %></Data></Cell>
        <Cell><Data ss:Type="String"><%= employee.last_name%></Data></Cell>
        <Cell><Data ss:Type="String"><%= employee.gender%></Data></Cell>
        <Cell><Data ss:Type="String"><%= employee.dob%></Data></Cell>
        <Cell><Data ss:Type="String"><%= employee.passportno%></Data></Cell>
        <Cell><Data ss:Type="String"><%= employee.pidate%></Data></Cell>
        <Cell><Data ss:Type="String"><%= employee.pedate%></Data></Cell>
        <Cell><Data ss:Type="String"><%= employee.iqamano%></Data></Cell>
        <Cell><Data ss:Type="String"><%= employee.iqidate%></Data></Cell>
        <Cell><Data ss:Type="String"><%= employee.iqedate%></Data></Cell>
        <Cell><Data ss:Type="String"><%= employee.insuranceno%></Data></Cell>
        <Cell><Data ss:Type="String"><%= employee.iidate%></Data></Cell>
        <Cell><Data ss:Type="String"><%= employee.iedate%></Data></Cell>
        <Cell><Data ss:Type="String"><%= employee.visano%></Data></Cell>
        <Cell><Data ss:Type="String"><%= employee.vidate%></Data></Cell>
        <Cell><Data ss:Type="String"><%= employee.vedate%></Data></Cell>
        <Cell><Data ss:Type="String"><%= employee.Marstatus%></Data></Cell>
        <Cell><Data ss:Type="String"><%= employee.religion%></Data></Cell>
        <Cell><Data ss:Type="String"><%= employee.nationality %></Data></Cell>
        <Cell><Data ss:Type="String"><%= employee.civstatus%></Data></Cell>
        <Cell><Data ss:Type="String"><%= employee.designation%></Data></Cell>
        <Cell><Data ss:Type="String"><%= employee.department%></Data></Cell>
        <Cell><Data ss:Type="String"><%= employee.speciali%></Data></Cell>
        <Cell><Data ss:Type="String"><%= employee.exp%></Data></Cell>
        <Cell><Data ss:Type="String"><%= employee.email%></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/employees/insurance.html.erb
<%- model_class = Employee -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th>S#</th>
      <th><%= model_class.human_attribute_name(:empno) %></th>
      <th><%= model_class.human_attribute_name(:first_name) %></th>
      <th><%= model_class.human_attribute_name(:insuranceno) %></th>
      <th><%= model_class.human_attribute_name(:iidate) %></th>
      <th><%= model_class.human_attribute_name(:iedate) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @employees.each_with_index do |employee,i| %>
      <tr>
        <td><%= link_to (i+1), employee_path(employee),{class: "link"}%></td>
        <td><%= employee.empno %></td>
        <td><%= link_to employee.first_name, employee_path(employee),{class: "link"} %></td>
        <td><%= employee.insuranceno %></td>
        <td><%= employee.iidate %></td>
        <td><%= employee.iedate %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_employee_path(employee), :class => 'btn btn-mini' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/employees/iqama.html.erb
<%- model_class = Employee -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th>S#</th>
      <th><%= model_class.human_attribute_name(:empno) %></th>
      <th><%= model_class.human_attribute_name(:first_name) %></th>
      <th><%= model_class.human_attribute_name(:iqamano) %></th>
      <th><%= model_class.human_attribute_name(:iqidate) %></th>
      <th><%= model_class.human_attribute_name(:iqedate) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @employees.each_with_index do |employee,i| %>
      <tr>
        <td><%= link_to (i+1), employee_path(employee),{class: "link"} %></td>
        <td><%= employee.empno %></td>
        <td><%= link_to employee.first_name, employee_path(employee),{class: "link"} %></td>
        <td><%= employee.iqamano %></td>
        <td><%= employee.iqidate %></td>
        <td><%= employee.iqedate %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_employee_path(employee), :class => 'btn btn-mini' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/employees/new.html.erb
<%- model_class = Employee -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/employees/passport.html.erb
<%- model_class = Employee -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>S#</th>
      <th><%= model_class.human_attribute_name(:empno) %></th>
      <th><%= model_class.human_attribute_name(:first_name) %></th>
      <th><%= model_class.human_attribute_name(:passportno) %></th>
      <th><%= model_class.human_attribute_name(:pidate) %></th>
      <th><%= model_class.human_attribute_name(:pedate) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>

 <tbody>
    <% @employees.each_with_index do |employee,i| %>
      <tr>
        <td><%= link_to (i+1), employee_path(employee),{class: "link"}  %></td>
        <td><%= employee.empno %></td>
        <td><%= link_to employee.first_name,employee_path(employee),{class: "link"} %></td>
        <td><%= employee.passportno %></td>
        <td><%= employee.pidate %></td>
        <td><%= employee.pedate %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_employee_path(employee), :class => 'btn btn-mini' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/employees/search.html.erb
<%- model_class = Employee -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>S#</th>
      <th><%= model_class.human_attribute_name(:empno) %></th>
      <th><%= model_class.human_attribute_name(:first_name) %></th>
      <th><%= model_class.human_attribute_name(:middle_name) %></th>
      <th><%= model_class.human_attribute_name(:last_name) %></th>
      <th><%= model_class.human_attribute_name(:gender) %></th>
      <th><%= model_class.human_attribute_name(:dob) %></th>
      <th><%= model_class.human_attribute_name(:nationality) %></th>
      <th><%= model_class.human_attribute_name(:designation) %></th>
      <th><%= model_class.human_attribute_name(:department) %></th>
      <th><%= model_class.human_attribute_name(:exp) %></th>
      <th><%= model_class.human_attribute_name(:passportno) %></th>
      <th><%= model_class.human_attribute_name(:pidate) %></th>
      <th><%= model_class.human_attribute_name(:pedate) %></th>
      <th><%= model_class.human_attribute_name(:iqamano) %></th>
      <th><%= model_class.human_attribute_name(:iqidate) %></th>
      <th><%= model_class.human_attribute_name(:iqedate) %></th>
      <th><%= model_class.human_attribute_name(:insuranceno) %></th>
      <th><%= model_class.human_attribute_name(:iidate) %></th>
      <th><%= model_class.human_attribute_name(:iedate) %></th>
      <th><%= model_class.human_attribute_name(:visano) %></th>
      <th><%= model_class.human_attribute_name(:vidate) %></th>
      <th><%= model_class.human_attribute_name(:vedate) %></th>
      <th><%= model_class.human_attribute_name(:Marstatus) %></th>
      <th><%= model_class.human_attribute_name(:religion) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @employees.each_with_index do |employee,i| %>
      <tr>
        <td><%= link_to (i+1), employee_path(employee),{class: "link"} %></td>
        <td><%= employee.empno %></td>
        <td><%= link_to employee.first_name,employee_path(employee),{class: "link"} %></td>
        <td><%= employee.middle_name %></td>
        <td><%= employee.last_name %></td>
        <td><%= employee.gender %></td>
        <td><%= employee.dob %></td>
        <td><%= employee.nationality %></td>
        <td><%= employee.designation %></td>
        <td><%= employee.department %></td>
        <td><%= employee.exp %></td>
        <td><%= employee.passportno%></td>
        <td><%= employee.pidate%></td>
        <td><%= employee.pedate%></td>
        <td><%= employee.iqamano%></td>
        <td><%= employee.iqidate%></td>
        <td><%= employee.iqedate%></td>
        <td><%= employee.insuranceno %></td>
        <td><%= employee.iidate%></td>
        <td><%= employee.iedate%></td>
        <td><%= employee.visano%></td>
        <td><%= employee.vidate%></td>
        <td><%= employee.vedate%></td>
        <td><%= employee.Marstatus%></td>
        <td><%= employee.religion %></td>
        <td><%= employee.email %></td>
        <td>

          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_employee_path(employee), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      employee_path(employee),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<div class="form-actions">
<%= link_to t('.new', :default => t("helpers.links.new")),
            new_employee_path,
            :class => 'btn btn-primary' %>
<%= link_to "To Excel",find_path(params.merge(format: 'xls')),:class => 'btn btn-mini' %>
</div>
<% if false %>
<ul>
  <%= @employees.each do |employee| %>
    <li><%= link_to employee.first_name,:action =>'show',:id =>employee.id  %></li>
  <% end %>
</ul>
<% end %>

app/views/employees/visa.html.erb
<%- model_class = Employee -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th>S#</th>
      <th><%= model_class.human_attribute_name(:empno) %></th>
      <th><%= model_class.human_attribute_name(:first_name) %></th>
      <th><%= model_class.human_attribute_name(:visano) %></th>
      <th><%= model_class.human_attribute_name(:vidate) %></th>
      <th><%= model_class.human_attribute_name(:vedate) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @employees.each_with_index do |employee,i| %>
      <tr>
        <td><%= link_to (i+1), employee_path(employee),{class: "link"} %></td>
        <td><%= employee.empno %></td>
        <td><%= link_to employee.first_name, employee_path(employee),{class: "link"} %></td>
        <td><%= employee.visano %></td>
        <td><%= employee.vidate %></td>
        <td><%= employee.vedate %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_employee_path(employee), :class => 'btn btn-mini' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>