config/routes.rb
HrsiteNew::Application.routes.draw do
  require File.expand_path("../../lib/authenticated_user",__FILE__)

  scope ":locale" ,locale: /#{I18n.available_locales.join("|")}/ do
    resources :sessions, only: [:new, :create, :destroy]
    resources :contracts
    resources :educations
    resources :employees
    resources :vehicles
    resources :documents
    resources :searches ,only: [:new,:create,:show]
    resources :users ,only:[:new,:create,:update]
    root to: 'static_pages#home', :constraints => AuthenticatedUser.new(true)
    root to: 'sessions#new', :constraints => AuthenticatedUser.new(false)
    match '/help', to: 'static_pages#help'
    match '/docshow', to: 'employees#docshow'
    match '/passport', to: 'employees#passport'
    match '/iqama', to: 'employees#iqama'
    match '/visa', to: 'employees#visa'
    match '/insurance', to: 'employees#insurance'
    match '/signin', to: 'sessions#new'
    match '/signout', to: 'sessions#destroy', via: :delete
    match '/find', to: 'employees#search'
  end
  match '*path', to: redirect("/#{I18n.default_locale}/%{path}")
  match '', to: redirect("/#{I18n.default_locale}")

end

app/models/document.rb
# == Schema Information
#
# Table name: documents
#
#  id         :integer         not null, primary key
#  empno      :string(255)
#  created_at :datetime        not null
#  updated_at :datetime        not null
#  sig        :string(255)
#  passport   :string(255)
#  iqama      :string(255)
#  visa       :string(255)
#
class Document < ActiveRecord::Base
  attr_accessible :empno,:visa,:sig,:passport,:iqama
  mount_uploader :visa, VisaUploader
  mount_uploader :sig, SigUploader
  mount_uploader :passport, PassportUploader
  mount_uploader :iqama, IqamaUploader
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
	before_filter :signed_in_user,
                only: [:index, :edit, :update, :destroy,:show,:new,:create]

  def index
    @documents = Document.all

    respond_to do |format|
      format.html # index.html.erb
      format.csv { render text: @documents.to_csv }
      format.xls #{send_data @documents.to_csv(col_sep: "\t")}
      format.json { render json: @documents }
    end
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
    @document = Document.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @document }
    end
  end

  # GET /employees/new
  # GET /employees/new.json
  def new
    @document = Document.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @document }
    end
  end

  # GET /employees/1/edit
  def edit
    @document = Document.find(params[:id])
  end

  # POST /employees
  # POST /employees.json
  def create
    @document = Document.new(params[:document])

    respond_to do |format|
      if @document.save
        format.html { redirect_to @document, notice: 'Document was successfully created.' }
        format.json { render json: @document, status: :created, location: @document }
      else
        format.html { render action: "new" }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /employees/1
  # PUT /employees/1.json
  def update
    @document = Document.find(params[:id])

    respond_to do |format|
      if @document.update_attributes(params[:document])
        format.html { redirect_to @document, notice: 'Document was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @document = Document.find(params[:id])
    @document.destroy
    respond_to do |format|
      format.html { redirect_to documents_url }
      format.json { head :no_content }
    end
  end

end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/_form.html.erb
<%- model_class = Document -%>
<%= simple_form_for @document, :html => {:multipart => true ,:class => 'form-horizontal' } do |f| %>
   <div class="control-group">
    <%= f.input :empno,collection: Employee.all,label_method: :empname,value_method: :empno,:include_blank => false,label: "Employee No"%>
  <div class="attach-set">
      <%= f.label model_class.human_attribute_name(:sig)%> &nbsp
      <%= f.file_field :sig %>
  </div><br>
     <div class="attach-set">
      <%= f.label model_class.human_attribute_name(:passport)%> &nbsp
      <%= f.file_field :passport %>
  </div><br>
    <div class="attach-set">
      <%= f.label model_class.human_attribute_name(:iqama)%> &nbsp
      <%= f.file_field :iqama %>
  </div><br>
    <div class="attach-set">
      <%= f.label model_class.human_attribute_name(:visa)%> &nbsp
      <%= f.file_field :visa %>
  </div> 


  <div class="form-actions">
    <%= f.button :submit ,:class => 'btn btn-primary'%>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),documents_path, :class => 'btn' %>
  </div>
</div>
<% end %>

app/views/documents/edit.html.erb
<%- model_class = Document -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/documents/index.html.erb
<%- model_class = Document -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>S#</th>
      <th><%= model_class.human_attribute_name(:empno) %></th>
      <th><%=t("documents.name")%></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @documents.each_with_index do |document,i| %>
      <tr>
        <td><%= link_to (i+1), document_path(document),{class: "link"} %></td>
        <td><%= link_to document.empno,document_path(document),{class: "link"} %></td>
        <td><% unless document.nil? %><%= Employee.find_by_empno(document.empno).send(:fullname) %><% end %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_document_path(document), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      document_path(document),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<div class="form-actions">
<%= link_to t('.new', :default => t("helpers.links.new")),
            new_document_path,
            :class => 'btn btn-primary' %>
</div>

app/views/documents/new.html.erb
<%- model_class = Document -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/documents/show.html.erb
<%- model_class = Document -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>
<br/>
<br/>
  <h5>Document Details</h5>
  <br/>
<table class="table table-striped">
  <tr>
    <td><%= model_class.human_attribute_name(:empno) %></td>
    <td><%= @document.empno %></td>
    <td></td>
  </tr>
  <tr>
    <td><%= model_class.human_attribute_name(:sig) %></td>
    <td><% unless @document.sig_url.nil? %><%= image_tag @document.sig_url(:display) %> </td>
    <td><%= link_to "Save",@document.sig_url(:display), :class => 'btn',:target => "_blank"%><% end %></td>
  </tr>
  <tr>
    <td><%= model_class.human_attribute_name(:passport) %></td>
    <td><% unless @document.passport_url.nil? %><%= image_tag @document.passport_url(:display) %></td>
    <td><%= link_to "Save",@document.passport_url(:display), :class => 'btn',:target => "_blank"  %><% end %></td>
  </tr>
  <tr>
    <td><%= model_class.human_attribute_name(:iqama) %></td>
    <td><% unless @document.iqama_url.nil? %><%= image_tag @document.iqama_url(:display) %></td>
    <td><%= link_to "Save",@document.iqama_url(:display), :class => 'btn',:target => "_blank"  %><% end %></td>
  </tr>
  <tr>
    <td><%= model_class.human_attribute_name(:visa) %></td>
    <td><% unless @document.visa_url.nil? %><%= image_tag @document.visa_url(:display) %></td>
    <td><%= link_to "Save",@document.visa_url(:display), :class => 'btn',:target => "_blank" %><% end %></td>
  </tr>
</table>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              documents_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_document_path(@document), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              document_path(@document),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>