config/routes.rb
HrsiteNew::Application.routes.draw do
  require File.expand_path("../../lib/authenticated_user",__FILE__)

  scope ":locale" ,locale: /#{I18n.available_locales.join("|")}/ do
    resources :sessions, only: [:new, :create, :destroy]
    resources :contracts
    resources :educations
    resources :employees
    resources :vehicles
    resources :documents
    resources :searches ,only: [:new,:create,:show]
    resources :users ,only:[:new,:create,:update]
    root to: 'static_pages#home', :constraints => AuthenticatedUser.new(true)
    root to: 'sessions#new', :constraints => AuthenticatedUser.new(false)
    match '/help', to: 'static_pages#help'
    match '/docshow', to: 'employees#docshow'
    match '/passport', to: 'employees#passport'
    match '/iqama', to: 'employees#iqama'
    match '/visa', to: 'employees#visa'
    match '/insurance', to: 'employees#insurance'
    match '/signin', to: 'sessions#new'
    match '/signout', to: 'sessions#destroy', via: :delete
    match '/find', to: 'employees#search'
  end
  match '*path', to: redirect("/#{I18n.default_locale}/%{path}")
  match '', to: redirect("/#{I18n.default_locale}")

end

app/models/search.rb
class Search < ActiveRecord::Base
  attr_accessible :doc, :edate
  
  def employees
    @employees ||= find_employees
  end
  
  private

    def find_employees
      employees = Employee.order(:empno)
      employees = employees.where("#{doc} <= ?", edate) if edate.present? and doc.present?
      employees
   end
end
# == Schema Information
#
# Table name: searches
#
#  id         :integer         not null, primary key
#  doc        :string(255)
#  edate      :date
#  created_at :datetime        not null
#  updated_at :datetime        not null
#

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  # GET /searches/1
  # GET /searches/1.json
  def show
    @search = Search.find(params[:id])


    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @search }
      format.xls
    end
  end

  # GET /searches/new
  # GET /searches/new.json
  def new
    @search = Search.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @search }
    end
  end

  # POST /searches
  # POST /searches.json
  def create
    @search = Search.new(params[:search])

    respond_to do |format|
      if @search.save
        format.html { redirect_to @search, notice: 'Search was performed.' }
        format.json { render json: @search, status: :created, location: @search }
      else
        format.html { render action: "new" }
        format.json { render json: @search.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/helpers/searches_helper.rb
module SearchesHelper
  
  def model_fields
    # which fields to display and sort by
    [:id,:empno, :first_name, :last_name, :email,:pedate,:iedate,:iqedate,:vedate,:gender]
  end

  def results_limit
    # max number of search results to display
    100
  end

  def display_query_sql(employee)
    "SQL: #{employee.to_sql}"
  end

  def display_results_header(count)
    if count > results_limit
      "Your first #{results_limit} results out of #{count} total"
    else
      "You have #{pluralize(count, 'result')}"
    end
  end

  def action
    action_name == 'advanced_search' ? :post : :get
  end

  def display_sort_column_headers(search)
    model_fields.each_with_object('') do |field, string|
      string << content_tag(:th,field)
    end
  end

  def display_search_results(objects)
    objects.limit(results_limit).each_with_object('') do |object, string|
      string << content_tag(:tr, display_search_results_row(object))
    end
  end

  def display_search_results_row(object)
    lol=model_fields
    id=lol[0]
    pass=lol[5]
    emp=lol[1]
    empl=0
    idl=0
    ide=0
    model_fields.each_with_object('') do |field, string|
      if field==id
        string << content_tag(:td,content_tag(:a,object.send(field),:href=>employee_path(object.send(field))))
        ide=object.send(field)
      elsif field==emp
        string << content_tag(:td,content_tag(:a,object.send(field),:href=>employee_path(ide)))
        empl=object.send(field)
      elsif field==pass
        idl=find_passport_id(empl)
        print idl
        string << content_tag(:td,content_tag(:a,object.send(field),:href=>document_path(idl)))
      else
        string << content_tag(:td,object.send(field))
      end
    end
    .html_safe
  end

  def find_passport_id(empl)
    Document.find(:all,:select => "id",:conditions =>['empno ILIKE ? ',empl])
  end

end

app/views/searches/_form.html.erb
<%= simple_form_for(@search,:html => { :class => 'form-inline' })  do |f| %>
  <%= f.error_notification %>

  <div class="control-group">
    <%= f.input :doc,collection: [[t("layouts.header.passport"),"pedate"],[t("layouts.header.visa"),"vedate"],[t("layouts.header.insurance"),"iedate"],[t("layouts.header.iqama"),"iqedate"]],:include_blank => false%>
    <%= f.input :edate%>
  </div>

  <div class="form-actions">
    <%= f.submit t("helpers.label.search.search").html_safe,:class => 'btn btn-primary'%>
  </div>
<% end %>

app/views/searches/new.html.erb
<%- model_class = Search -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<%= render 'form' %>

app/views/searches/show.html.erb
<div class="page-header">
<%= content_tag :h2, display_results_header(@search.employees.size) %>
</div>
<% if false %>
 <%= content_tag :table do %>
 <%= content_tag :thead, display_sort_column_headers(@search), nil, false %>
 <% end %>
<% end %>
<br/>
<br/>
<table class="table table-striped lol">
  <thead>
    <th>Id</th>
  	<th>Empno</th>
  	<th>First Name</th>
  	<th>Last Name</th>
  	<th>Email</th>
  	<th>Passport Expiry</th>
  	<th>Insurance Expiry</th>
  	<th>Iqama Expiry</th>
  	<th>Visa Expiry</th>
    <th>Gender</th>
  </thead>
<%= content_tag :tbody, display_search_results(@search.employees), nil, false %>
</table>
<div class="form-actions">
<%= link_to 'Back',new_search_path,:class => 'btn btn-mini' %>
<%= link_to "To Excel",search_path(params.merge(format: 'xls')),:class => 'btn btn-mini' %>
</div>

app/views/searches/show.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">Employee No</Data></Cell>
        <Cell><Data ss:Type="String">First Name</Data></Cell>
        <Cell><Data ss:Type="String">Last Name</Data></Cell>
        <Cell><Data ss:Type="String">Email</Data></Cell>
      </Row>




    <% @search.employees.each do |s| %>
      <Row>
        <Cell><Data ss:Type="String"><%= s.empno %></Data></Cell>
        <Cell><Data ss:Type="String"><%= s.first_name %></Data></Cell>
        <Cell><Data ss:Type="String"><%= s.last_name%></Data></Cell>
        <Cell><Data ss:Type="String"><%= s.email%></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>