config/routes.rb
HrsiteNew::Application.routes.draw do
  require File.expand_path("../../lib/authenticated_user",__FILE__)

  scope ":locale" ,locale: /#{I18n.available_locales.join("|")}/ do
    resources :sessions, only: [:new, :create, :destroy]
    resources :contracts
    resources :educations
    resources :employees
    resources :vehicles
    resources :documents
    resources :searches ,only: [:new,:create,:show]
    resources :users ,only:[:new,:create,:update]
    root to: 'static_pages#home', :constraints => AuthenticatedUser.new(true)
    root to: 'sessions#new', :constraints => AuthenticatedUser.new(false)
    match '/help', to: 'static_pages#help'
    match '/docshow', to: 'employees#docshow'
    match '/passport', to: 'employees#passport'
    match '/iqama', to: 'employees#iqama'
    match '/visa', to: 'employees#visa'
    match '/insurance', to: 'employees#insurance'
    match '/signin', to: 'sessions#new'
    match '/signout', to: 'sessions#destroy', via: :delete
    match '/find', to: 'employees#search'
  end
  match '*path', to: redirect("/#{I18n.default_locale}/%{path}")
  match '', to: redirect("/#{I18n.default_locale}")

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://palmate.in/">palmate</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",'http://palmate.in/aboutus.htm' %></li>
      <li><%= link_to "Contact us", 'mailto:info@palmate.in' %></li>
   </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
    <div class="navbar-inner">
      <div class="container">
      <% if false%>
        <%= link_to image_tag("palback_w.jpeg",alt: "Palmate"),"http://www.palmate.in", id: "logo" %>
      <% end %>
        <%= link_to image_tag("Untitled.jpeg",alt: "Palmate"),"http://www.palmate.in", id: "logo" %>
        <nav>
          <ul class="nav pull-left">
            <li><%= link_to t("layouts.header.home").html_safe,root_path %></li>
            <%if false %>
            <li><%= link_to t("layouts.header.help").html_safe,help_path %></li>
            <%end %>
            <% if signed_in? %>
            <li><%= link_to t("layouts.header.employees").html_safe ,employees_path %></li>
            <li><%= link_to t("layouts.header.educations").html_safe,educations_path %></li>
            <li><%= link_to t("layouts.header.contracts").html_safe,contracts_path %></li>
            <li><%= link_to t("layouts.header.search").html_safe,new_search_path %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <%=t("layouts.header.documents").html_safe%> <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to t("layouts.header.passport").html_safe,passport_path%></li>
                <li><%= link_to t("layouts.header.iqama").html_safe,iqama_path%></li>
                <li><%= link_to t("layouts.header.insurance").html_safe,insurance_path%></li>
                <li><%= link_to t("layouts.header.visa").html_safe,visa_path%></li>
                <li><%= link_to t("layouts.header.upload").html_safe,documents_path%></li>
              </ul>
            </li>
            <li><%= link_to t("layouts.header.vehicles").html_safe ,vehicles_path %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <%= t("layouts.header.accounts").html_safe %> <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to t("layouts.header.settings").html_safe,new_user_path%></li>
                <li class="divider"></li>
                <li>
                  <%= link_to t("layouts.header.signout").html_safe, signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% end %>
          </ul>
        
          <ul class="nav pull-right">
            <li>  <%= link_to_unless_current t("layouts.header.english").html_safe, locale: "en" %></li>
            <li>  <%= link_to_unless_current t("layouts.header.arabic").html_safe, locale: "ar" %></li>
           <% if signed_in? %>  
            <%= form_tag find_path,:controller => 'employees',:method => :get,:action => 'search',:class => 'navbar-search pull-right' do %>
              <%= text_field_tag :keyword,params[:keyword],:id => 'search_field' ,class: "search-query",placeholder: "Search" %>
            <%end%>
          </ul>
          <% end %>
        </nav>
      </div>
    </div>
  </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag "application", :media => :all %>
  <%= stylesheet_link_tag "print", :media => :print %>
  <link href='http://fonts.googleapis.com/css?family=Telex' rel='stylesheet' type='text/css'>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <!--<link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css" rel="stylesheet">-->
  <!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
  <meta name="viewport" content="width=device-width, initial-scale=1.0"> 
  <%= render 'layouts/shim' %>
</head>
<body>
  <div id="wrap">
    <div id="main" class="container clear-top">
      <%= render 'layouts/header' %>
      <div class="lol">
        <% if signed_in? %>
          <%= link_to_function(raw("<span class='glyphicon glyphicon-print'></span>Print This page &nbsp"),"javascript:print()",:class => 'btn btn-primary btn-print') %>
        <% end %>
    </div>
        <div class="container">
          <% flash.each do |key, value| %>
          <%= content_tag(:div, value, class: "alert alert-#{key}") %>
          <% end %>
          <%= yield %>
        </div>
    </div>
  </div>
   <div class="container">      
    <%= render 'layouts/footer' %>
   </div>


</body>
</html>